### ISSUE TITLE
open by serial number not working

### ISSUE THREAD

**Issue by mossmann** [greatscottgadgets/greatfet#186]
```python
>>> import greatfet
>>> gf=greatfet.GreatFET(serial_number="000057cc67e630318c57")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/GreatFET-0.0-py3.6.egg/greatfet/greatfet.py", line 31, in GreatFET
    return GreatFETBoard.autodetect(**board_identifiers)
  File "/usr/lib/python3.6/site-packages/pygreat-0.0-py3.6.egg/pygreat/board.py", line 77, in autodetect
pygreat.errors.DeviceNotFoundError
>>> gf=greatfet.GreatFET()
>>> gf.serial_number()
'000057cc67e630318c57'
```

**Comment by mossmann** [comment]
It works when given the 32 character serial number reported by lsusb -vv (000000000000000057cc67e630318c57), but it does not work with the abbreviated serial number reported by gf info.
