### ISSUE TITLE
setup.py: KeyError: 'commitcount'

### ISSUE THREAD

**Issue by mossmann** [greatscottgadgets/greatfet#227]
```
$ python3 setup.py build
Traceback (most recent call last):
  File "setup.py", line 78, in <module>
    **setup_options
  File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 444, in __init__
    k: v for k, v in attrs.items()
  File "/usr/lib/python3.6/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 732, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/mossmann/src/greatfet/host/.eggs/better_setuptools_git_version-1.0.5-py3.6.egg/better_setuptools_git_version.py", line 82, in validate_version_config
    dist.metadata.version = get_version(template, starting_version)
  File "/home/mossmann/src/greatfet/host/.eggs/better_setuptools_git_version-1.0.5-py3.6.egg/better_setuptools_git_version.py", line 59, in get_version
    version = template.format(tag=tag, sha=sha)
KeyError: 'commitcount'
```

**Comment by mossmann** [comment]
This is on e733294cb3753afe1a9f37887ef40166bc37f20e
