### ISSUE TITLE
Python2: No module named boards.flash_stub

### ISSUE THREAD

**Issue by mossmann** [greatscottgadgets/greatfet#252]
This happened after installing greatfet-2019.5.1.dev0 with pip2:

```
$ gf info
Found a GreatFET One!
  Board ID: 0
  Firmware version: git-2019.5.1.dev0
  Part ID: a0000a30604f5e
  Serial number: 000057cc67e6306f5357
 
$ gf shell
Traceback (most recent call last):
  File "/usr/local/bin/greatfet_shell", line 6, in <module>
    from greatfet.commands.greatfet_shell import main
  File "/usr/local/lib/python2.7/dist-packages/greatfet/commands/greatfet_shell.py", line 13, in <module>
    from greatfet.utils import GreatFETArgumentParser
  File "/usr/local/lib/python2.7/dist-packages/greatfet/utils.py", line 16, in <module>
    from greatfet.boards.flash_stub import GreatFETFlashStub
ImportError: No module named boards.flash_stub
```

I was able to workaround the problem by uninstalling with pip2 and installing from source, but I'm not sure if this is something that has been fixed or if it is something having to do with the installation method.

**Comment by mossmann** [comment]
I'm assuming this has been fixed because I could not reproduce the error after installing a .whl produced by `make prepare_release`.
