### ISSUE TITLE
greatfet logic drops samples at higher sample rates

### ISSUE THREAD

**Issue by mossmann** [greatscottgadgets/greatfet#286]
On my system it starts dropping samples at about 6 MB/s.  I used to get 17 MB/s reliably, and I would like to get 40+ MB/s.

To test I ran `./greatfet_logic.py -f 6000000 -n 8 -O | dd of=/dev/null status=progress` for 100 seconds.

Results:
```
with -n 8:
34000000 sps: 14.6 MB/s
17000000 sps: 11.3 MB/s
12000000 sps: 10.3 MB/s
10200000 sps:  9.0 MB/s
 8500000 sps:  8.1 MB/s
 6000000 sps:  5.9 MB/s
 4000000 sps:  4.0 MB/s
 2000000 sps:  2.0 MB/s

with -n 4:
12000000 sps:  5.9 MB/s
 6000000 sps:  5.3 MB/s

with -n 2:
12000000 sps:  8.1 MB/s
 6000000 sps:  6.0 MB/s

with -n 1:
12000000 sps: 11.1 MB/s
 6000000 sps:  6.0 MB/s
```

**Comment by mossmann** [comment]
@ktemkin was able to reproduce this on a Dell XPS 13 (similar to my test platform), but interestingly was able to achieve much higher speeds on different host hardware.

hackrf_transfer achieves 43 MB/s on my XPS 13, so, whatever host-specific issue the XPS 13 has, it doesn't affect HackRF (with basically the same microcontroller and very similar firmware).

**Comment by ktemkin** [comment]
From what I can tell, it seems like the process of submitting / "reaping" an URB takes significantly longer on some hardware platforms than others. This would explain why HackRF doesn't display the relevant behavior on those machines (as asynchronous transactions effectively submit their URBs in parallel with data being handled, so a long URB-submission time doesn't result in an overrun).

I've experimentally created a branch where the core codebase has been switched over from `pyusb` to `python-libusb1`; and added a benchmarking tool to that codebase:

https://github.com/ktemkin/GreatFET/tree/python-libusb1

@mossmann Can you try that codebase (using my branch `python-libusb1` on both greatfet and libgreat; and installing new versions of the firmware, host, and pygreat?)

I'd appreciate it if you could try to reproduce the following two tests, and post your results:

```
$ gf benchmark --sync-usb
Starting a benchmark of synchronous USB communications: transferring 128.0 MiB.
Transferred 128.0 MiB in 3.379885486 seconds. (Speed: 37.87 MiB/s)

$ gf benchmark --async-usb
Starting a benchmark of asynchronous USB communications: transferring 128.0 MiB.
Transferred 128.0 MiB in 2.8872006089999998 seconds. (Speed: 44.33 MiB/s)
```

**Comment by mossmann** [comment]
I'm getting:
```
$ gf benchmark --sync-usb
Traceback (most recent call last):
  File "/usr/bin/greatfet_benchmark", line 11, in <module>
    load_entry_point('GreatFET==2019.5.1', 'console_scripts', 'greatfet_benchmark')()
  File "/usr/lib64/python3.6/site-packages/GreatFET-2019.5.1-py3.6.egg/greatfet/commands/greatfet_benchmark.py", line 161, in main
    run_sync_benchmark(gf, args.length)
  File "/usr/lib64/python3.6/site-packages/GreatFET-2019.5.1-py3.6.egg/greatfet/commands/greatfet_benchmark.py", line 31, in run_sync_benchmark
    gf.comms.device.claimInterface(1)
AttributeError: 'Device' object has no attribute 'claimInterface'
```

**Comment by mossmann** [comment]
I get:
```
$ gf benchmark --sync-usb
Traceback (most recent call last):
  File "/usr/bin/greatfet_benchmark", line 11, in <module>
    load_entry_point('GreatFET==2019.5.1+dirty', 'console_scripts', 'greatfet_benchmark')()
  File "/usr/lib64/python3.6/site-packages/GreatFET-2019.5.1+dirty-py3.6.egg/greatfet/commands/greatfet_benchmark.py", line 161, in main
    run_sync_benchmark(gf, args.length)
  File "/usr/lib64/python3.6/site-packages/GreatFET-2019.5.1+dirty-py3.6.egg/greatfet/commands/greatfet_benchmark.py", line 31, in run_sync_benchmark
    gf.comms.device.claimInterface(1)
AttributeError: 'Device' object has no attribute 'claimInterface'
```
Is this device maybe using pyusb instead of libusb1?  (I don't get this far unless both are installed.)

**Comment by ktemkin** [comment]
That sounds like it’s loading the wrong pygreat— can you confirm that the pygreat that’s being loaded is from my corresponding libgreat branch?

(You’ll still need pyusb; I didn’t remove all of the references to it in that test.)

**Comment by mossmann** [comment]
Oops.  You are correct.  I cleaned things up, and it works:
```
 $ gf benchmark --sync-usb
Starting a benchmark of synchronous USB communications: transferring 128.0 MiB.
Transferred 128.0 MiB in 5.55133864202071 seconds. (Speed: 23.06 MiB/s)
$ gf benchmark --async-usb
Starting a benchmark of asynchronous USB communications: transferring 128.0 MiB.
Transferred 128.0 MiB in 2.9583105180063285 seconds. (Speed: 43.27 MiB/s)
```
Also it makes my laptop much louder!  There seems to be some audio information leakage that is hitting a resonant frequency.  :)

**Comment by mossmann** [comment]
I repeated some of the tests from my original post:
```
with -n 8:
34000000 sps: 33.4 MB/s
12000000 sps: 10.8 MB/s
 6000000 sps:  5.9 MB/s
 4000000 sps:  4.0 MB/s

with -n 4:
12000000 sps:  6.3 MB/s
 6000000 sps:  5.9 MB/s

with -n 2:
12000000 sps:  8.7 MB/s
 6000000 sps:  6.0 MB/s

with -n 1:
12000000 sps: 11.1 MB/s
 6000000 sps:  6.0 MB/s
```
Asynchronous USB definitely helps a great deal, but there is still room for improvement.  So far it looks like the remaining slowness is mostly in sample unpacking on the host.

**Comment by ktemkin** [comment]
Yeah; the pure-python sample unpacking doesn't work super well. I have some ideas to improve them; but they haven't been a priority.

**Comment by mossmann** [comment]
Now async USB is working perfectly for me. I was able to achieve 102 Msps with -n 2 by skipping the unpacking:
https://github.com/mossmann/greatfet/tree/python-libusb1
