### ISSUE TITLE
Python errors in Windows and linux

### ISSUE THREAD

**Issue by Legion303** [greatscottgadgets/greatfet#356]
Both systems are running Python 3.9 and have been updated but I can't get this brand-new board to do anything.

64-bit Ubuntu 16.04 on VMWare Player 15:

~/.local/bin$ gf info
Traceback (most recent call last):
  File "/home/analyst/.local/lib/python3.5/site-packages/pygreat/comms_backends/usb.py", line 353, in execute_raw_command
    self.LIBGREAT_REQUEST_NUMBER, self.LIBGREAT_VALUE_EXECUTE, flags, to_send, timeout)
  File "/home/analyst/.local/lib/python3.5/site-packages/usb/core.py", line 1077, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/home/analyst/.local/lib/python3.5/site-packages/usb/backend/libusb1.py", line 901, in ctrl_transfer
    timeout))
  File "/home/analyst/.local/lib/python3.5/site-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 5] Input/Output Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/analyst/.local/lib/python3.5/site-packages/pygreat/comms_backends/usb.py", line 418, in abort_command
    result = execute_abort(self.device)
  File "/home/analyst/.local/lib/python3.5/site-packages/pygreat/comms_backends/usb.py", line 414, in <lambda>
    self.LIBGREAT_ERRNO_SIZE, timeout)
  File "/home/analyst/.local/lib/python3.5/site-packages/usb/core.py", line 1077, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/home/analyst/.local/lib/python3.5/site-packages/usb/backend/libusb1.py", line 901, in ctrl_transfer
    timeout))
  File "/home/analyst/.local/lib/python3.5/site-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 5] Input/Output Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/analyst/.local/bin/greatfet_info", line 11, in <module>
    sys.exit(main())
  File "/home/analyst/.local/lib/python3.5/site-packages/greatfet/commands/greatfet_info.py", line 125, in main
    devices = GreatFET(find_all=True)
  File "/home/analyst/.local/lib/python3.5/site-packages/greatfet/greatfet.py", line 31, in GreatFET
    return GreatFETBoard.autodetect_all(**board_identifiers)
  File "/home/analyst/.local/lib/python3.5/site-packages/pygreat/board.py", line 105, in autodetect_all
    subclass_devices = subclass.all_accepted_devices(**device_identifiers)
  File "/home/analyst/.local/lib/python3.5/site-packages/pygreat/board.py", line 151, in all_accepted_devices
    if cls.accepts_connected_device(**identifiers):
  File "/home/analyst/.local/lib/python3.5/site-packages/pygreat/board.py", line 179, in accepts_connected_device
    raise e
  File "/home/analyst/.local/lib/python3.5/site-packages/pygreat/board.py", line 168, in accepts_connected_device
    potential_device = cls(**device_identifiers)
  File "/home/analyst/.local/lib/python3.5/site-packages/greatfet/boards/rad1o.py", line 24, in __init__
    super(Rad1oBadge, self).__init__(**device_identifiers)
  File "/home/analyst/.local/lib/python3.5/site-packages/greatfet/board.py", line 86, in __init__
    super(GreatFETBoard, self).__init__(*args, **kwargs)
  File "/home/analyst/.local/lib/python3.5/site-packages/pygreat/board.py", line 245, in __init__
    if self.HANDLED_BOARD_IDS and (self.board_id() not in self.HANDLED_BOARD_IDS):
  File "/home/analyst/.local/lib/python3.5/site-packages/pygreat/board.py", line 274, in board_id
    return self.apis.core.read_board_id()
  File "/home/analyst/.local/lib/python3.5/site-packages/pygreat/comms.py", line 1109, in method
    timeout=timeout, max_response_length=max_response_length, encoding=encoding, *arguments)
  File "/home/analyst/.local/lib/python3.5/site-packages/pygreat/comms.py", line 1264, in execute_command
    out_format, *arguments, **kwargs)
  File "/home/analyst/.local/lib/python3.5/site-packages/pygreat/comms.py", line 771, in execute_command
    None, max_response_length, comms_timeout, pretty_name, rephrase_errors)
  File "/home/analyst/.local/lib/python3.5/site-packages/pygreat/comms_backends/usb.py", line 382, in execute_raw_command
    error_number = self.abort_command()
  File "/home/analyst/.local/lib/python3.5/site-packages/pygreat/comms_backends/usb.py", line 422, in abort_command
    result = execute_abort(self.device)
  File "/home/analyst/.local/lib/python3.5/site-packages/pygreat/comms_backends/usb.py", line 414, in <lambda>
    self.LIBGREAT_ERRNO_SIZE, timeout)
  File "/home/analyst/.local/lib/python3.5/site-packages/usb/core.py", line 1077, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/home/analyst/.local/lib/python3.5/site-packages/usb/backend/libusb1.py", line 901, in ctrl_transfer
    timeout))
  File "/home/analyst/.local/lib/python3.5/site-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 5] Input/Output Error

Windows 10, 64-bit:

C:\Windows\System32>gf info
Traceback (most recent call last):
  File "c:\users\steve\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\steve\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\steve\AppData\Local\Programs\Python\Python39\Scripts\greatfet_info.exe\__main__.py", line 7, in <module>
  File "c:\users\steve\appdata\local\programs\python\python39\lib\site-packages\greatfet\commands\greatfet_info.py", line 125, in main
    devices = GreatFET(find_all=True)
  File "c:\users\steve\appdata\local\programs\python\python39\lib\site-packages\greatfet\greatfet.py", line 31, in GreatFET
    return GreatFETBoard.autodetect_all(**board_identifiers)
  File "c:\users\steve\appdata\local\programs\python\python39\lib\site-packages\pygreat\board.py", line 105, in autodetect_all
    subclass_devices = subclass.all_accepted_devices(**device_identifiers)
  File "c:\users\steve\appdata\local\programs\python\python39\lib\site-packages\pygreat\board.py", line 151, in all_accepted_devices
    if cls.accepts_connected_device(**identifiers):
  File "c:\users\steve\appdata\local\programs\python\python39\lib\site-packages\pygreat\board.py", line 168, in accepts_connected_device
    potential_device = cls(**device_identifiers)
  File "c:\users\steve\appdata\local\programs\python\python39\lib\site-packages\greatfet\board.py", line 86, in __init__
    super(GreatFETBoard, self).__init__(*args, **kwargs)
  File "c:\users\steve\appdata\local\programs\python\python39\lib\site-packages\pygreat\board.py", line 245, in __init__
    if self.HANDLED_BOARD_IDS and (self.board_id() not in self.HANDLED_BOARD_IDS):
  File "c:\users\steve\appdata\local\programs\python\python39\lib\site-packages\pygreat\board.py", line 274, in board_id
    return self.apis.core.read_board_id()
  File "c:\users\steve\appdata\local\programs\python\python39\lib\site-packages\pygreat\comms.py", line 1108, in method
    return self.execute_command(verb_number, in_format, out_format, name=name, class_name=class_name,
  File "c:\users\steve\appdata\local\programs\python\python39\lib\site-packages\pygreat\comms.py", line 1263, in execute_command
    return self.comms_backend.execute_command(self.CLASS_NUMBER, verb, in_format,
  File "c:\users\steve\appdata\local\programs\python\python39\lib\site-packages\pygreat\comms.py", line 770, in execute_command
    raw_result = self.execute_raw_command(class_number, verb, payload, timeout,
  File "c:\users\steve\appdata\local\programs\python\python39\lib\site-packages\pygreat\comms_backends\usb.py", line 377, in execute_raw_command
    return response.tostring()
AttributeError: 'array.array' object has no attribute 'tostring'

**Comment by Legion303** [comment]
Update: I have the same "tostring" error on another linux VM on a second computer and another Win10 install on a third computer. All 64-bit, all running Python3.9. Is there an issue with 3.9?

**Comment by Legion303** [comment]
Update again: uninstalled Python 3.9, installed Python 3.7.2, looks like that solved the problem. Might need to specify the version number in the setup guides until it's compatible?
