### ISSUE TITLE
AttributeError: 'array.array' object has no attribute 'tostring'

### ISSUE THREAD

**Issue by kylma** [greatscottgadgets/greatfet#360]
Hi there,

I'm following the getting started tutorial and I'm getting this error when executing `greatfet info`

```
greatfet info -H
Host tools info:
	host module version: 2020.1.2
	pygreat module version: 2020.1.2
	python version: 3.9.1 (default, Dec 13 2020, 11:55:53)

	module path: /home/kylma/.local/lib/python3.9/site-packages/greatfet
	command path: /home/kylma/.local/lib/python3.9/site-packages/greatfet/commands
	gnuradio-companion block path: /home/kylma/.local/lib/python3.9/site-packages/greatfet/gnuradio


Traceback (most recent call last):
  File "/home/kylma/.local/bin/greatfet_info", line 8, in <module>
    sys.exit(main())
  File "/home/kylma/.local/lib/python3.9/site-packages/greatfet/commands/greatfet_info.py", line 125, in main
    devices = GreatFET(find_all=True)
  File "/home/kylma/.local/lib/python3.9/site-packages/greatfet/greatfet.py", line 31, in GreatFET
    return GreatFETBoard.autodetect_all(**board_identifiers)
  File "/home/kylma/.local/lib/python3.9/site-packages/pygreat/board.py", line 105, in autodetect_all
    subclass_devices = subclass.all_accepted_devices(**device_identifiers)
  File "/home/kylma/.local/lib/python3.9/site-packages/pygreat/board.py", line 151, in all_accepted_devices
    if cls.accepts_connected_device(**identifiers):
  File "/home/kylma/.local/lib/python3.9/site-packages/pygreat/board.py", line 168, in accepts_connected_device
    potential_device = cls(**device_identifiers)
  File "/home/kylma/.local/lib/python3.9/site-packages/greatfet/boards/rad1o.py", line 24, in __init__
    super(Rad1oBadge, self).__init__(**device_identifiers)
  File "/home/kylma/.local/lib/python3.9/site-packages/greatfet/board.py", line 86, in __init__
    super(GreatFETBoard, self).__init__(*args, **kwargs)
  File "/home/kylma/.local/lib/python3.9/site-packages/pygreat/board.py", line 245, in __init__
    if self.HANDLED_BOARD_IDS and (self.board_id() not in self.HANDLED_BOARD_IDS):
  File "/home/kylma/.local/lib/python3.9/site-packages/pygreat/board.py", line 274, in board_id
    return self.apis.core.read_board_id()
  File "/home/kylma/.local/lib/python3.9/site-packages/pygreat/comms.py", line 1108, in method
    return self.execute_command(verb_number, in_format, out_format, name=name, class_name=class_name,
  File "/home/kylma/.local/lib/python3.9/site-packages/pygreat/comms.py", line 1263, in execute_command
    return self.comms_backend.execute_command(self.CLASS_NUMBER, verb, in_format,
  File "/home/kylma/.local/lib/python3.9/site-packages/pygreat/comms.py", line 770, in execute_command
    raw_result = self.execute_raw_command(class_number, verb, payload, timeout,
  File "/home/kylma/.local/lib/python3.9/site-packages/pygreat/comms_backends/usb.py", line 377, in execute_raw_command
    return response.tostring()
AttributeError: 'array.array' object has no attribute 'tostring'
```

**Comment by ktemkin** [comment]
Looks like this needs to be updated for python@3.9; it should be `tobytes` and not `tostring`. `tostring` was there for py2 compatibility; but since we've dropped py2 a year ago, we can also drop that.

@Qyriad can you take care of this?
