### ISSUE TITLE
Windows 10 - [Errno5]Input/Output error

### ISSUE THREAD

**Issue by markoHUN** [greatscottgadgets/greatfet#365]
usb.core.USBError: [Errno 5] Input/Output Error

I get this type of error message during the setup stage of Greatfet One. Do you know if there is any possible solution for this?
I get similart error as in #327 case.

C:\Users\hpelitebook>gf info
Traceback (most recent call last):
  File "c:\users\hpelitebook\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\hpelitebook\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\hpelitebook\AppData\Local\Programs\Python\Python39\Scripts\greatfet_info.exe\__main__.py", line 7, in <module>
  File "c:\users\hpelitebook\appdata\local\programs\python\python39\lib\site-packages\greatfet\commands\greatfet_info.py", line 125, in main
    devices = GreatFET(find_all=True)
  File "c:\users\hpelitebook\appdata\local\programs\python\python39\lib\site-packages\greatfet\greatfet.py", line 31, in GreatFET
    return GreatFETBoard.autodetect_all(**board_identifiers)
  File "c:\users\hpelitebook\appdata\local\programs\python\python39\lib\site-packages\pygreat\board.py", line 105, in autodetect_all
    subclass_devices = subclass.all_accepted_devices(**device_identifiers)
  File "c:\users\hpelitebook\appdata\local\programs\python\python39\lib\site-packages\pygreat\board.py", line 151, in all_accepted_devices
    if cls.accepts_connected_device(**identifiers):
  File "c:\users\hpelitebook\appdata\local\programs\python\python39\lib\site-packages\pygreat\board.py", line 179, in accepts_connected_device
    raise e
  File "c:\users\hpelitebook\appdata\local\programs\python\python39\lib\site-packages\pygreat\board.py", line 168, in accepts_connected_device
    potential_device = cls(**device_identifiers)
  File "c:\users\hpelitebook\appdata\local\programs\python\python39\lib\site-packages\greatfet\boards\legacy.py", line 76, in __init__
    if self.HANDLED_BOARD_IDS and (self.board_id() not in self.HANDLED_BOARD_IDS):
  File "c:\users\hpelitebook\appdata\local\programs\python\python39\lib\site-packages\greatfet\boards\legacy.py", line 112, in board_id
    response = self.vendor_request_in(self.REQUEST_READ_BOARD_ID, length=1)
  File "c:\users\hpelitebook\appdata\local\programs\python\python39\lib\site-packages\greatfet\boards\legacy.py", line 235, in vendor_request_in
    return self._vendor_request(usb.ENDPOINT_IN, request, length,
  File "c:\users\hpelitebook\appdata\local\programs\python\python39\lib\site-packages\greatfet\boards\legacy.py", line 221, in _vendor_request
    return self.device.ctrl_transfer(
  File "c:\users\hpelitebook\appdata\local\programs\python\python39\lib\site-packages\usb\core.py", line 1072, in ctrl_transfer
    ret = self._ctx.backend.ctrl_transfer(
  File "c:\users\hpelitebook\appdata\local\programs\python\python39\lib\site-packages\usb\backend\libusb1.py", line 893, in ctrl_transfer
    ret = _check(self.lib.libusb_control_transfer(
  File "c:\users\hpelitebook\appdata\local\programs\python\python39\lib\site-packages\usb\backend\libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])

**Comment by markoHUN** [comment]
I found a solution for this problem. While installing the driver with Zadig I used libusbK, NOT libusb-win32. Now it works.
