### ISSUE TITLE
No i2c available error

### ISSUE THREAD

**Issue by whatnick** [greatscottgadgets/greatfet#394]
Environment:
Python 3.9
Windows 10
Zadig driver installed

Error:
```
Spawning an IPython shell for easy access to your GreatFET board.
Like normal python, you can use help(object) to get help for that object.

Try help(gf.gpio) to see the documentation for the GreatFET GPIO;
try dir(gf) to see a list of properties on the GreatFET object, and
try gf.available_interfaces() and gf.available_programmers() to see
the interfaces you can work with, and the programmers you can create.

This GreatFET shell is *magical*. Try some of our IPython magics:

         %dmesg      -- prints the GreatFET's debug ring (log)
         %reconnect  -- tries to reconnect to the current GreatFET
         %makeflash  -- when run from a firmware build dir, builds and flashes your GreatFET
         %reload     -- tries to reload your host python code; useful with $PYTHONPATH
         %refet      -- (not %reset) resets and reconnects to the current GreatFET
                        [hey, %reset was taken!]


A GreatFET object has been created for you as 'gf'. Have fun!

Traceback (most recent call last):
  File "E:\whatnick\casr_velograph\Velograph\venv\Scripts\greatfet_shell-script.py", line 33, in <module>
    sys.exit(load_entry_point('GreatFET==2019.5.1', 'console_scripts', 'greatfet_shell')())
  File "E:\whatnick\casr_velograph\Velograph\venv\lib\site-packages\greatfet\commands\greatfet_shell.py", line 76, in main
    i2c =  gf.i2c
AttributeError: 'GreatFETOne' object has no attribute 'i2c'
```

**Comment by straithe** [comment]
Can you run `gf_info -H` and paste the output here?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
